/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/site-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSiteSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/service-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Snapshot for the live-service banner; also streamed over SSE on the `service-status` topic. */
        get: operations["getServiceStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description text/event-stream. `topics` is a comma-separated list (e.g. `service-status,testimonials,event-availability:evt_123`). Each event's `event:` field is the topic name; `data:` is the JSON payload for that topic's resource. Supports `Last-Event-ID` for resume. */
        get: operations["getLiveStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sermons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSermons"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sermons/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSermon"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sermon-series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSermonSeries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sermon-series/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSermonSeries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ministries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMinistries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ministries/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMinistry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLeaders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaders/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLeader"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLocations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLocation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blog-posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listBlogPosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blog-posts/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBlogPost"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/testimonials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTestimonials"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/giving/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listGivingAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/giving/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listGivingCampaigns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Admin-composed block pages, rendered by `app/[slug]/page.tsx` via `<BlockRenderer>`. */
        get: operations["getPage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forms/contact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitContactForm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forms/prayer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitPrayerRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forms/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitConnectCard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forms/newsletter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["subscribeNewsletter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Address: {
            streetAddress: string;
            locality: string;
            region?: string;
            country: string;
            mapUrl?: string;
        };
        ServiceTime: {
            dayOfWeek: string[];
            /** @example 09:00 */
            opens: string;
            /** @example 11:00 */
            closes?: string;
            /** @example Sunday Worship */
            label: string;
            /** @example Africa/Lagos */
            timezone?: string;
        };
        SocialLinks: {
            facebook?: string;
            instagram?: string;
            youtube?: string;
            tiktok?: string;
            x?: string;
            whatsapp?: string;
        };
        SiteSettings: {
            name: string;
            description?: string;
            logoUrl?: string;
            phone?: string;
            email?: string;
            address?: components["schemas"]["Address"];
            socialLinks?: components["schemas"]["SocialLinks"];
            serviceTimes?: components["schemas"]["ServiceTime"][];
            announcement?: {
                enabled?: boolean;
                text?: string;
                href?: string;
            };
            hero?: components["schemas"]["Hero"];
            /** @description Short statements of what the church is about, authored by the church. */
            pillars?: components["schemas"]["Pillar"][];
        };
        Cta: {
            label: string;
            href: string;
        };
        /** @description Homepage hero, authored by the church. Every field is optional. */
        Hero: {
            headline?: string;
            headlineAccent?: string;
            subheadline?: string;
            media?: {
                /** @enum {string} */
                kind: "image" | "video";
                url: string;
                /** @description Still frame shown before/instead of video. */
                posterUrl?: string;
                alt?: string;
            };
            primaryCta?: components["schemas"]["Cta"];
            secondaryCta?: components["schemas"]["Cta"];
        };
        Pillar: {
            title: string;
            description?: string;
        };
        ServiceStatus: {
            isLive: boolean;
            /** @example Sunday Worship */
            label?: string;
            streamUrl?: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            nextServiceAt?: string;
        };
        Speaker: {
            id: string;
            name: string;
            photoUrl?: string;
        };
        SermonSeries: {
            id: string;
            slug: string;
            title: string;
            description?: string;
            coverUrl?: string;
            sermonCount?: number;
        };
        Sermon: {
            id: string;
            slug: string;
            title: string;
            description?: string;
            speaker?: components["schemas"]["Speaker"];
            series?: components["schemas"]["SermonSeries"];
            videoUrl?: string;
            audioUrl?: string;
            thumbnailUrl?: string;
            /** Format: date-time */
            publishedAt: string;
            durationSeconds?: number;
            scripture?: string[];
            topics?: string[];
        };
        SermonPage: {
            items: components["schemas"]["Sermon"][];
            nextCursor?: string | null;
        };
        Event: {
            id: string;
            slug: string;
            title: string;
            description?: string;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt?: string;
            isOnline?: boolean;
            locationName?: string;
            coverUrl?: string;
            registerUrl?: string | null;
            capacity?: number | null;
            seatsTaken?: number | null;
            ministrySlug?: string | null;
        };
        EventPage: {
            items: components["schemas"]["Event"][];
            nextCursor?: string | null;
        };
        Ministry: {
            id: string;
            slug: string;
            name: string;
            summary?: string;
            descriptionHtml?: string;
            coverUrl?: string;
            meetingSchedule?: string;
            leader?: components["schemas"]["Speaker"];
        };
        Leader: {
            id: string;
            slug: string;
            name: string;
            role?: string;
            bio?: string;
            photoUrl?: string;
            order?: number;
        };
        Location: {
            id: string;
            slug: string;
            name: string;
            isMain?: boolean;
            address?: components["schemas"]["Address"];
            phone?: string;
            coverUrl?: string;
            serviceTimes?: components["schemas"]["ServiceTime"][];
        };
        BlogPost: {
            id: string;
            slug: string;
            title: string;
            excerpt?: string;
            contentHtml?: string;
            coverUrl?: string;
            authorName?: string;
            /** Format: date-time */
            publishedAt: string;
            /** Format: date-time */
            updatedAt?: string;
            tags?: string[];
        };
        BlogPostPage: {
            items: components["schemas"]["BlogPost"][];
            nextCursor?: string | null;
        };
        Testimonial: {
            id: string;
            name: string;
            photoUrl?: string;
            quote: string;
            /** Format: date-time */
            submittedAt: string;
        };
        GivingAccount: {
            id: string;
            label: string;
            bankName: string;
            accountNumber: string;
            accountName: string;
            /** @example NGN */
            currency?: string;
        };
        GivingCampaign: {
            id: string;
            title: string;
            description?: string;
            goalAmount: number;
            raisedAmount: number;
            currency: string;
            /** Format: date-time */
            endsAt?: string | null;
        };
        Block: {
            /** @enum {string} */
            type: "hero" | "richText" | "mediaSplit" | "cardGrid" | "ctaBanner" | "faq" | "gallery" | "scriptureQuote";
            data?: {
                [key: string]: unknown;
            };
        };
        Page: {
            slug: string;
            title: string;
            description?: string;
            blocks: components["schemas"]["Block"][];
        };
        ContactSubmission: {
            name: string;
            /** Format: email */
            email: string;
            phone?: string;
            subject?: string;
            message: string;
        };
        PrayerSubmission: {
            name: string;
            /** Format: email */
            email?: string;
            phone?: string;
            request: string;
            isConfidential?: boolean;
        };
        ConnectSubmission: {
            name: string;
            /** Format: email */
            email: string;
            phone?: string;
            /** @enum {string} */
            interest: "visit" | "membership" | "groups" | "volunteering" | "baptism";
            notes?: string;
        };
        NewsletterSubmission: {
            /** Format: email */
            email: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSiteSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteSettings"];
                };
            };
        };
    };
    getServiceStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceStatus"];
                };
            };
        };
    };
    getLiveStream: {
        parameters: {
            query: {
                topics: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
        };
    };
    listSermons: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
                series?: string;
                speaker?: string;
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SermonPage"];
                };
            };
        };
    };
    getSermon: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sermon"];
                };
            };
        };
    };
    listSermonSeries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SermonSeries"][];
                };
            };
        };
    };
    getSermonSeries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SermonSeries"];
                };
            };
        };
    };
    listEvents: {
        parameters: {
            query?: {
                view?: "upcoming" | "past" | "all";
                ministry?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
        };
    };
    listMinistries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ministry"][];
                };
            };
        };
    };
    getMinistry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ministry"];
                };
            };
        };
    };
    listLeaders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Leader"][];
                };
            };
        };
    };
    getLeader: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Leader"];
                };
            };
        };
    };
    listLocations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"][];
                };
            };
        };
    };
    getLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"];
                };
            };
        };
    };
    listBlogPosts: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
                tag?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlogPostPage"];
                };
            };
        };
    };
    getBlogPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlogPost"];
                };
            };
        };
    };
    listTestimonials: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Testimonial"][];
                };
            };
        };
    };
    listGivingAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GivingAccount"][];
                };
            };
        };
    };
    listGivingCampaigns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GivingCampaign"][];
                };
            };
        };
    };
    getPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
        };
    };
    submitContactForm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ContactSubmission"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    submitPrayerRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PrayerSubmission"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    submitConnectCard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ConnectSubmission"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    subscribeNewsletter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["NewsletterSubmission"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
