import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { buildOrganizationSchema } from "@/lib/seo/jsonld";
import { getSiteSettings } from "@/domain/site/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const settings = await getSiteSettings();
  const organizationSchema = buildOrganizationSchema({
    name: settings.name,
    description: settings.description,
    logoUrl: settings.logoUrl,
    phone: settings.phone,
    email: settings.email,
    address: settings.address,
    sameAs: Object.values(settings.socialLinks).filter((value): value is string => Boolean(value)),
    serviceTimes: settings.serviceTimes.map(service => ({
      dayOfWeek: service.dayOfWeek,
      opens: service.opens,
      closes: service.closes ?? service.opens,
      description: service.label,
    })),
  });

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
